name: Build RPM Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: fedora-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo dnf groupinstall "Development Tools" -y
        sudo dnf install -y cmake rpm-build qt5-qtbase-devel qt5-qtsvg-devel qt5-qttools-devel qt5-qtmultimedia-devel libtag-devel libicu-devel gsettings-qt-devel dbus-devel kf5-kcodecs-devel ffmpeg-devel dtkwidget-devel vlc-devel udisks2-devel

    - name: Build project
      run: |
        mkdir -p Build
        cd Build
        cmake ..
        make

    - name: Create RPM package
      run: |
        cd Build
        mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp ../path-to-source.tar.gz rpmbuild/SOURCES/
        cp ../path-to-spec-file.spec rpmbuild/SPECS/
        rpmbuild -ba rpmbuild/SPECS/path-to-spec-file.spec

    - name: Upload RPM package
      uses: actions/upload-artifact@v3
      with:
        name: rpm-package
        path: rpmbuild/RPMS/
