name: Create RPM Package for Deepin Music

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu as the build environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools and dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake pkg-config qtbase5-dev qt5-qmake qttools5-dev-tools qtmultimedia5-dev \
                            libtag1-dev libicu-dev libgsettings-qt-dev libdbusextended-qt5-dev libkf5codecs-dev \
                            libavutil-dev libavcodec-dev libavformat-dev libdtkcore-dev libdtkgui-dev \
                            libdframeworkdbus-dev libudisks2-dev libvlc-dev libvlccore-dev dtk5-dev \
                            rpm build-essential

    - name: Build deepin-music
      run: |
        mkdir -p Build
        cd Build
        cmake ..
        make

    - name: Prepare RPM build structure
      run: |
        mkdir -p rpm/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        tar -czvf rpm/SOURCES/deepin-music.tar.gz -C .. .

    - name: Create deepin-music.spec file
      run: |
        cat <<EOF > rpm/SPECS/deepin-music.spec
        Name: deepin-music
        Version: 1.0
        Release: 1%{?dist}
        Summary: Deepin Music Player RPM Package

        License: GPL
        Source: deepin-music.tar.gz

        BuildRequires: cmake, gcc, make, qt5-qmake, qtbase5-dev, libtag1-dev, libavutil-dev, \
                       libavcodec-dev, libavformat-dev, libvlc-dev, libvlccore-dev, \
                       libdtkcore-dev, libdtkgui-dev, libdframeworkdbus-dev, libudisks2-dev, \
                       libkf5codecs-dev, libicu-dev, libgsettings-qt-dev, libdbusextended-qt5-dev
        Requires: qt5, libtag1, libavutil, libavcodec, libavformat, libvlc, libvlccore, \
                  dtkcore, dtkgui, dframeworkdbus, udisks2, kf5codecs, libicu, gsettings-qt, \
                  dbus

        %description
        Deepin Music Player is an awesome music player built by the Deepin project.

        %prep
        %setup -q

        %build
        mkdir -p Build
        cd Build
        cmake ..
        make

        %install
        mkdir -p %{buildroot}/usr/bin
        install -m 0755 Build/deepin-music %{buildroot}/usr/bin/

        %files
        /usr/bin/deepin-music

        %changelog
        * Thu Oct 14 2024 burhanverse <burhanverse@proton.me> 1.0
        - Initial RPM release for Deepin Music
        EOF

    - name: Build RPM package
      run: |
        rpmbuild -ba rpm/SPECS/deepin-music.spec --define "_topdir $(pwd)/rpm"

    - name: Upload RPM package
      uses: actions/upload-artifact@v3
      with:
        name: deepin-music-rpm
        path: rpm/RPMS/
